### ISSUE TITLE
[FIXED] NoMethodError: undefined method `binds_from_relation'

### ISSUE THREAD

**Issue by tmartyny** [ConsultingMD/activerecord5-redshift-adapter#17]
After updating to Rails 5.2.0, we began to see this error:
```
NoMethodError: undefined method `binds_from_relation' for #<ActiveRecord::ConnectionAdapters::RedshiftAdapter:0x0000000002e678a8>
/usr/local/lib/rvm/gems/ruby-2.4.2/bundler/gems/activerecord5-redshift-adapter-4d0303a77298/lib/active_record/connection_adapters/redshift/database_statements.rb:48:in `select_value'
/usr/local/lib/rvm/gems/ruby-2.4.2/bundler/gems/activerecord5-redshift-adapter-4d0303a77298/lib/active_record/connection_adapters/redshift/schema_statements.rb:99:in `data_source_exists?'
```

binds_from_relation is a private method in this module: https://github.com/rails/rails/blob/b7b0e5c1fd0ebb73b3fde5b2c059bcfd63aa07c4/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L391

This private method was removed

**Comment by himberjack** [comment]
+1

**Comment by elioncho** [comment]
+1

**Comment by arsro** [comment]
+1

**Comment by tmartyny** [comment]
resolved with this PR merge: https://github.com/ConsultingMD/activerecord5-redshift-adapter/pull/19
