### ISSUE TITLE
ArgumentError - wrong number of arguments (given 2, expected 0..1) on Rails 5.2.1

### ISSUE THREAD

**Issue by DucNguyenVan** [ConsultingMD/activerecord5-redshift-adapter#22]
Hi, 
Im upgrading from Rails 4.2 to Raisl 5.2.1
So I must change  activerecord4-redshift-adapter to activerecord5-redshift-adapter too.
When I start server `rails s`, it through out errors
```
rgumentError - wrong number of arguments (given 2, expected 0..1):
  activerecord (5.2.1) lib/active_record/errors.rb:100:in `initialize'
  activerecord5-redshift-adapter (1.0.1) lib/active_record/connection_adapters/redshift_adapter.rb:569:in `new'
  activerecord5-redshift-adapter (1.0.1) lib/active_record/connection_adapters/redshift_adapter.rb:569:in `rescue in connect'
  activerecord5-redshift-adapter (1.0.1) lib/active_record/connection_adapters/redshift_adapter.rb:564:in `connect'
  activerecord5-redshift-adapter (1.0.1) lib/active_record/connection_adapters/redshift_adapter.rb:198:in `initialize'
  activerecord5-redshift-adapter (1.0.1) lib/active_record/connection_adapters/redshift_adapter.rb:42:in `new'
  activerecord5-redshift-adapter (1.0.1) lib/active_record/connection_adapters/redshift_adapter.rb:42:in `redshift_connection'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
  activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
  activerecord (5.2.1) lib/active_record/connection_handling.rb:118:in `retrieve_connection'
  activerecord (5.2.1) lib/active_record/connection_handling.rb:90:in `connection'
  activerecord (5.2.1) lib/active_record/migration.rb:554:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
  actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
  web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
  web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
  web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
  activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
  activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
  activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
  railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  rack (2.0.5) lib/rack/method_override.rb:22:in `call'
  rack (2.0.5) lib/rack/runtime.rb:22:in `call'
  activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
  actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
  rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
  rack (2.0.5) lib/rack/deflater.rb:34:in `call'
  railties (5.2.1) lib/rails/engine.rb:524:in `call'
  rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
  puma (3.8.2) lib/puma/configuration.rb:224:in `call'
  puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
  puma (3.8.2) lib/puma/server.rb:435:in `process_client'
  puma (3.8.2) lib/puma/server.rb:299:in `block in run'
  puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
Do others have experienced similar problems? Does someone has an idea for a possible solution/ workaround?

**Comment by DucNguyenVan** [comment]
After read the source code, I think problem was PG
https://github.com/ConsultingMD/activerecord5-redshift-adapter/blob/master/lib/active_record/connection_adapters/redshift_adapter.rb#L563
```
        def connect
          @connection = PG::Connection.connect(@connection_parameters)

          configure_connection
        rescue ::PG::Error => error
          if error.message.include?("does not exist")
            raise ActiveRecord::NoDatabaseError.new(error.message, error)
          else
            raise
          end
        end
```
