### ISSUE TITLE
ArgumentError: wrong number of arguments on Rails 5.2.2

### ISSUE THREAD

**Issue by andyklimczak** [ConsultingMD/activerecord5-redshift-adapter#23]
Rails 5.2.2
Activerecord 5.2.2
Ruby 2.5.1

Was working with `activerecord4-redshift-adapter`. Thinking it's a config value issue, but not sure

```
 ArgumentError: wrong number of arguments (given 3, expected 2)
/usr/local/bundle/gems/activerecord5-redshift-adapter-1.0.1/lib/active_record/connection_adapters/redshift/schema_definitions.rb:57:in `create_column_definition'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:422:in `new_column_definition'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:366:in `column'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:232:in `block in string'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:232:in `each'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:232:in `string'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/internal_metadata.rb:37:in `block in create_table'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:305:in `create_table'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/internal_metadata.rb:36:in `create_table'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/migration.rb:1188:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/migration.rb:1036:in `new'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/migration.rb:1036:in `up'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/railties/databases.rake:60:in `block (2 levels) in &lt;main&gt;'
/usr/local/bundle/gems/secondbase-2.1.6/lib/second_base/databases.rake:37:in `block (4 levels) in &lt;main&gt;'
/usr/local/bundle/gems/secondbase-2.1.6/lib/second_base/on_base.rb:23:in `on_base'
/usr/local/bundle/gems/secondbase-2.1.6/lib/second_base/databases.rake:37:in `block (3 levels) in &lt;main&gt;'
/usr/local/bundle/gems/secondbase-2.1.6/lib/second_base/databases.rake:143:in `block (2 levels) in &lt;main&gt;' 
```

**Comment by gupsydaisys** [comment]
You need to talk to IT about having past employees getting these
notifications.  This is a privacy concern for Grand Rounds and might
require infosec!

**Comment by soonahn** [comment]
@gupsydaisys so 
1) This project is actually public and many people outside of GR use it.  I believe OP is a non GR employee who has an actual issue with the repo.
2) It's a lot easier to just ignore the emails, or just reply to them hilariously once in a while.

**Comment by gupsydaisys** [comment]
Yup, my bad.  Unsubscribed.  Thanks.
